# Generated by Django 2.2.5 on 2020-05-13 10:10

from django.db import migrations, models

DEFAULT_TEXTS = {
    'experiment-browsing': {
        'en': 'Newest experiments',
        'sv': 'De senaste försöken',
        'fi': 'Uusimmat kokeilut'
    }
}

def add_missing_default_editable_texts(apps, schema_editor):
    EditableText = apps.get_model('sitemap', 'EditableText')
    EditableText.__bases__ = (models.Model,)
    EditableTextTranslation = apps.get_model('sitemap', 'EditableTextTranslation')
    for text_type, values in DEFAULT_TEXTS.items():
        editable_text = EditableText(
            text_type=text_type
        )
        editable_text.save()
        for language, text_value in values.items():
            trans = EditableTextTranslation(
                master=editable_text,
                language_code=language,
                text_value=text_value
            )
            trans.save()

class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0005_remove_experimentchallenge_lead_text_2'),
        ('sitemap', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_experiments',
            field=models.ManyToManyField(blank=True, to='experiments.Experiment', verbose_name='featured experiments'),
        ),
        migrations.AlterField(
            model_name='editabletext',
            name='text_type',
            field=models.CharField(choices=[('front_page_header', 'Front page header'), ('front_page_ingress', 'Front page ingress'), ('stages-header', 'Stages header'), ('stage-1-header', 'Stage 1 header'), ('stage-2-header', 'Stage 2 header'), ('stage-3-header', 'Stage 3 header'), ('stage-1-text', 'Stage 1 text'), ('stage-2-text', 'Stage 2 text'), ('stage-3-text', 'Stage 3 text'), ('what-are-you-waiting', 'What are you waiting for text'), ('footer-paragraph', 'Footer paragraph'), ('experiment-browsing', 'Experiment browsing')], max_length=100, unique=True, verbose_name='text type'),
        ),
        migrations.RunPython(add_missing_default_editable_texts, reverse_code=lambda a, b: None)
    ]
