# Generated by Django 2.2.5 on 2020-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0004_siteconfiguration_funded_experiments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='front_page_image_opacity',
            field=models.FloatField(default=1.0, verbose_name='front page image opacity'),
        ),
    ]
