# Generated by Django 2.2.5 on 2020-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0005_siteconfiguration_front_page_image_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_menu_opacity',
            field=models.FloatField(default=0.25, verbose_name='top menu opacity'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='front_page_image_opacity',
            field=models.FloatField(default=0.1, verbose_name='front page image opacity'),
        ),
    ]
