# Generated by Django 2.2.12 on 2020-12-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0006_auto_20200518_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editabletext',
            name='text_type',
            field=models.CharField(choices=[('front_page_header', 'Front page header'), ('front_page_ingress', 'Front page ingress'), ('stages-header', 'Stages header'), ('stage-1-header', 'Stage 1 header'), ('stage-2-header', 'Stage 2 header'), ('stage-3-header', 'Stage 3 header'), ('stage-1-text', 'Stage 1 text'), ('stage-2-text', 'Stage 2 text'), ('stage-3-text', 'Stage 3 text'), ('what-are-you-waiting', 'What are you waiting for text'), ('footer-paragraph', 'Footer paragraph'), ('experiment-browsing', 'Experiment browsing'), ('experiment-search-header', 'Experiment search header')], max_length=100, unique=True, verbose_name='text type'),
        ),
    ]
