# Generated by Django 2.2.5 on 2020-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook account URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instagram account URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='LinkedIn account URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter account URL'),
        ),
    ]
