# Generated by Django 2.2.5 on 2020-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200415_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offering',
            field=models.ManyToManyField(blank=True, related_name='offering_userprofile_set', to='users.UserLookingForOption', verbose_name='offering'),
        ),
    ]
